In [2]:
import pandas as pd

# Load the dataset (local CSV previously saved)
df = pd.read_csv('adult_income.csv')

# Clean up whitespace in string columns
for col in df.select_dtypes(include='object'):
    df[col] = df[col].str.strip()

df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [3]:
from sklearn.model_selection import train_test_split

# Define target and feature set
target = 'income'
train_data, test_data = train_test_split(df, test_size=0.2, random_state=42)

print(f"Train shape: {train_data.shape}, Test shape: {test_data.shape}")

Train shape: (26048, 15), Test shape: (6513, 15)

In [4]:
from autogluon.tabular import TabularPredictor

# Create and train the AutoML predictor
predictor = TabularPredictor(label=target, eval_metric='accuracy').fit(
    train_data,
    time_limit=120  # seconds = 2 minutes
)

/Users/sandilranasinghe/Work/workshops/datastorm/code/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
No path specified. Models will be saved in: "AutogluonModels/ag-20250430_110005"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.2
Python Version:     3.12.8
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 24.1.0: Thu Oct 10 21:06:23 PDT 2024; root:xnu-11215.41.3~3/RELEASE_ARM64_T8132
CPU Count:          10
Memory Avail:       9.47 GB / 24.00 GB (39.4%)
Disk Space Avail:   337.23 GB / 460.43 GB (73.2%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='experimental' : New in v1.2: Pre-trained foundation model + parallel fits. The absolute best accuracy without consideration for inference speed. Does not support GPU.
	presets='best'         : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='high'         : Strong accuracy with fast inference speed.
	presets='good'         : Good accuracy with very fast inference speed.
	presets='medium'       : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 120s
AutoGluon will save models to "/Users/sandilranasinghe/Work/workshops/datastorm/code/AutogluonModels/ag-20250430_110005"
Train Data Rows:    26048
Train Data Columns: 14
Label Column:       income
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['>50K', '<=50K']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = >50K, class 0 = <=50K
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (>50K) vs negative (<=50K) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9665.55 MB
	Train Data (Original)  Memory Usage: 12.73 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', [])    : 6 | ['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss', ...]
		('object', []) : 8 | ['workclass', 'education', 'marital_status', 'occupation', 'relationship', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 7 | ['workclass', 'education', 'marital_status', 'occupation', 'relationship', ...]
		('int', [])       : 6 | ['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss', ...]
		('int', ['bool']) : 1 | ['sex']
	0.1s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 1.39 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.09597665847665848, Train Rows: 23548, Val Rows: 2500
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models, fit_strategy="sequential" ...
Fitting model: KNeighborsUnif ... Training model for up to 119.88s of the 119.88s of remaining time.
	0.7788	 = Validation score   (accuracy)
	2.41s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 117.43s of the 117.43s of remaining time.
	0.7748	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 117.40s of the 117.40s of remaining time.
	0.8684	 = Validation score   (accuracy)
	2.16s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 115.20s of the 115.20s of remaining time.
	0.8688	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 114.59s of the 114.59s of remaining time.
	0.8528	 = Validation score   (accuracy)
	3.53s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 110.95s of the 110.95s of remaining time.
	0.8524	 = Validation score   (accuracy)
	0.79s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 110.07s of the 110.07s of remaining time.
	0.8752	 = Validation score   (accuracy)
	10.41s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 99.65s of the 99.65s of remaining time.
	0.8544	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 98.97s of the 98.97s of remaining time.
	0.8516	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 98.26s of the 98.26s of remaining time.
No improvement since epoch 8: early stopping
	0.8576	 = Validation score   (accuracy)
	8.52s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 89.71s of the 89.71s of remaining time.
	0.8724	 = Validation score   (accuracy)
	0.92s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 88.77s of the 88.77s of remaining time.
	0.852	 = Validation score   (accuracy)
	9.67s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 79.09s of the 79.09s of remaining time.
	0.87	 = Validation score   (accuracy)
	2.12s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 119.88s of the 76.95s of remaining time.
	Ensemble Weights: {'CatBoost': 1.0}
	0.8752	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 43.13s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 677900.2 rows/s (2500 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (2500 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/sandilranasinghe/Work/workshops/datastorm/code/AutogluonModels/ag-20250430_110005")

In [5]:
# Predict on test set
y_pred = predictor.predict(test_data)
score = predictor.evaluate(test_data)

# View leaderboard
predictor.leaderboard(test_data, silent=True)

/Users/sandilranasinghe/Work/workshops/datastorm/code/venv/lib/python3.12/site-packages/fastai/learner.py:455: UserWarning: load_learner` uses Python's insecure pickle module, which can execute malicious arbitrary code when loading. Only load files you trust.
If you only need to load model weights and optimizer state, use the safe `Learner.load` instead.
  warn("load_learner` uses Python's insecure pickle module, which can execute malicious arbitrary code when loading. Only load files you trust.\nIf you only need to load model weights and optimizer state, use the safe `Learner.load` instead.")

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,CatBoost,0.879625,0.8752,accuracy,0.010897,0.003048,10.405194,0.010897,0.003048,10.405194,1,True,7
1,WeightedEnsemble_L2,0.879625,0.8752,accuracy,0.011505,0.003688,10.467925,0.000608,0.000640,0.062731,2,True,14
2,XGBoost,0.877936,0.8724,accuracy,0.014935,0.009977,0.924178,0.014935,0.009977,0.924178,1,True,11
3,LightGBM,0.876094,0.8688,accuracy,0.006936,0.004952,0.601483,0.006936,0.004952,0.601483,1,True,4
4,LightGBMXT,0.875019,0.8684,accuracy,0.035566,0.026885,2.162210,0.035566,0.026885,2.162210,1,True,3
5,LightGBMLarge,0.874559,0.8700,accuracy,0.009067,0.004269,2.120936,0.009067,0.004269,2.120936,1,True,13
6,RandomForestEntr,0.865193,0.8524,accuracy,0.114678,0.038105,0.786419,0.114678,0.038105,0.786419,1,True,6
7,RandomForestGini,0.861508,0.8528,accuracy,0.108201,0.038048,3.529132,0.108201,0.038048,3.529132,1,True,5
8,NeuralNetFastAI,0.860740,0.8576,accuracy,0.049400,0.014022,8.518632,0.049400,0.014022,8.518632,1,True,10
9,NeuralNetTorch,0.858591,0.8520,accuracy,0.018903,0.008239,9.672961,0.018903,0.008239,9.672961,1,True,12
10,ExtraTreesEntr,0.855827,0.8516,accuracy,0.155165,0.050181,0.567678,0.155165,0.050181,0.567678,1,True,9
11,ExtraTreesGini,0.855520,0.8544,accuracy,0.158653,0.037792,0.569466,0.158653,0.037792,0.569466,1,True,8
12,KNeighborsUnif,0.779364,0.7788,accuracy,0.016008,0.036236,2.410427,0.016008,0.036236,2.410427,1,True,1
13,KNeighborsDist,0.768617,0.7748,accuracy,0.015886,0.014272,0.011202,0.015886,0.014272,0.011202,1,True,2

In [8]:
# Show feature importance
importance_df = predictor.feature_importance(test_data)

importance_df.head(n=20)

Computing feature importance via permutation shuffling for 14 features using 5000 rows with 5 shuffle sets...
	1.27s	= Expected runtime (0.25s per shuffle set)
	0.42s	= Actual runtime (Completed 5 of 5 shuffle sets)

                importance    stddev   p_value  n  p99_high   p99_low
capital_gain       0.05076  0.003201  0.000002  5  0.057351  0.044169
relationship       0.02236  0.002651  0.000023  5  0.027819  0.016901
occupation         0.02140  0.002627  0.000027  5  0.026809  0.015991
age                0.02028  0.003354  0.000087  5  0.027187  0.013373
capital_loss       0.01448  0.000934  0.000002  5  0.016403  0.012557
marital_status     0.01228  0.002194  0.000117  5  0.016797  0.007763
education_num      0.00900  0.001606  0.000117  5  0.012307  0.005693
hours_per_week     0.00484  0.001431  0.000819  5  0.007787  0.001893
workclass          0.00472  0.002361  0.005532  5  0.009580 -0.000140
education          0.00364  0.002076  0.008613  5  0.007914 -0.000634
sex                0.00176  0.001228  0.016376  5  0.004288 -0.000768
fnlwgt             0.00088  0.001045  0.066408  5  0.003032 -0.001272
native_country     0.00056  0.000654  0.064074  5  0.001907 -0.000787
race               0.00016  0.000865  0.350167  5  0.001941 -0.001621